### ISSUE TITLE
expiresInMinutes and expiresInSeconds is deprecated

### ISSUE THREAD

**Issue by komocode** [ghaiklor/sails-service-cipher#22]
Getting errors:
jsonwebtoken: expiresInMinutes and expiresInSeconds is deprecated. (.../node_modules/sails-service-cipher/lib/JwtCipher.js:117:14)
app-0 (err): Use "expiresIn" expressed in seconds.

**Comment by ghaiklor** [comment]
@komocode Did you try to update your dependencies?

**Comment by komocode** [comment]
Alright, looks like I got to update everything make the switch to Node 4. Too many dependencies to go through. I'll close the ticket and will open another if I have any issues. Thanks.
